# Generated by Django 3.1.5 on 2021-01-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='complited',
            new_name='completed',
        ),
    ]
